### ISSUE TITLE
App crashes as soon as its opened

### ISSUE THREAD

**Issue by EvaxTheFox** [acmo0/Android-Youtube-Downloader#5]
Hi so I have a problem, the app crashes as soon as it launches, here is the error: I am on Android 12 
`java.lang.IllegalArgumentException: com.acmo0.youtubedownloader: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
`

**Comment by acmo0** [comment]
Hello,
thank you for reporting this issue. I will try to fix this in the next few days.

**Comment by MystWalkerOfficial** [comment]
any updates? same issue here

**Comment by acmo0** [comment]
Yes, I discovered that how the app is build makes it impossible to run on android 10 and above. I have to rebuilt the application almost from scratch which will take a while. If you have a linux computer I would recommend you to use the linux app which is on an other repo (which does the same thing) while I make all the changes to make the application working on Android 10 and above.

**Comment by sougoukk** [comment]
我修改了所有的crash也运行起来了。。但是无法嗅探视频。。。

**Comment by Boris-rnd** [comment]
Same issue on Redmi Note 12

**Comment by acmo0** [comment]
Actually I just start to code a new version of the application from scratch, the future version will work from android 8 to android 10 at least. However, I don't know when the developpement phase will be finished.

**Comment by acmo0** [comment]
Even if the issue is due to a flag which is missing to start a PendingIntent, your android version should be android 10 or above so fixing the flag issue should not fix the main issue of the app.
